### ISSUE TITLE
GameTime.py 文件中有两行的缩进有问题

### ISSUE THREAD

**Issue by homer12** [pokemonchw/dieloli#12]
我试着去运行这个游戏，提示说这个地方有 Syntax Error

https://github.com/pokemonchw/dieloli/blob/master/script/Design/GameTime.py#L238
https://github.com/pokemonchw/dieloli/blob/master/script/Design/GameTime.py#L239

不知道该如何提交报告，感觉不值得特地开一个pull request，就用issue的方式了

**Comment by pokemonchw** [comment]
检查了一下，是在对 [CourseSession.json](https://github.com/pokemonchw/dieloli/blob/master/data/chinese/CourseSession.json) 这个文件的数据结构进行修改时改漏了结构导致的，因为在之前的优化中对数据进行了预处理，所以一直没发现这个bug，感谢反馈，已修复
