### ISSUE TITLE
Win10跑game.py提示AttributeError: module 'time' has no attribute 'tzset'

### ISSUE THREAD

**Issue by hansixue** [pokemonchw/dieloli#123]
下release里的包也有相同的问题，只不过一闪而过就闪退了。
也没生成error.log，可能#81的老哥说的问题和我是一个。
随手查了下报错的函数是只能unix用的，是不是去linux下玩比较好？

**Comment by hansixue** [comment]
> linux下因为fork机制的关系，性能之类的会好不少....win下不支持tzset的话，待我调整一下看看

嗯嗯，刚刚在LINUX下正常玩了（虽然不知道为啥我一丝不挂和同学搭话还吓到人家了= =|||）
不过可以的话还是想在WIN下打，因为其他黄油也都在win这里...

**Comment by pokemonchw** [comment]
因为你没穿衣服，npc会自己穿衣服，玩家需要玩家自己手动操作，然后，这个bug我正在连夜修复

**Comment by pokemonchw** [comment]
修好了哦，测一下看看？

**Comment by hansixue** [comment]
抱歉加班现在才测试，确实可以打开了。
我去玩耍了
