### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by princessGasmask** [pokemonchw/dieloli#144]
Is there a way to play in English yet, or are we still waiting for a translation?

**Comment by pokemonchw** [comment]
Sorry, I didn't know there were non Chinese players.

**Comment by arthurming123** [comment]
It's possible to do UI translations even without any knowledge of Chinese (looking at the Python code); UI translations could be simply lifted from there.

**Comment by pokemonchw** [comment]
At the current stage, you can create a "en_us" directory, copy the "dieloli.po" file under [this path](https://github.com/pokemonchw/dieloli/blob/master/data/po/zh_CN/LC_MESSAGES/), fill in the "msgstr" in it, and modify the [script](https://github.com/pokemonchw/dieloli/blob/master/buildmo.py) and the config generated under the game directory Ini, you can switch to English. I'm glad you're willing to help with this. I'll improve the process. I just need to help with the dieloli.po file

**Comment by arthurming123** [comment]
Sounds interesting.

For clarification, so for something like this.
```
#: Script/UI/Panel/see_map_panel.py:328
#, python-brace-format
msgid "{scene_id}:{scene_name}:{move_time}分钟"
msgstr ""
```
It will become like this right?
```
#: Script/UI/Panel/see_map_panel.py:328
#, python-brace-format
msgid "{scene_id}:{scene_name}:{move_time}分钟"
msgstr "{scene_id}:{scene_name}:{move_time}minutes"
```

**Comment by princessGasmask** [comment]
I followed the steps for localization, but my game is still in Chinese. I don't know what I'm doing wrong.

**Comment by pokemonchw** [comment]
Maybe you didn't generate the corresponding mo file and change the config.ini setting. Don't worry. I have done better localization management in the next version, including automatic processing of po files, automatic updating of mo data, language switching and setting in the game
@princessGasmask

**Comment by StonePick** [comment]
It seems that the progress is slow. Maybe I can do some help?

**Comment by pokemonchw** [comment]
Now we have a relatively complete localization solution. When you edit the po files, the translations will be automatically updated upon game startup. Also, switching languages in the game settings is now working properly. Therefore, I've decided to temporarily close this issue.
