### ISSUE TITLE
No module named 'freetype'

### ISSUE THREAD

**Issue by LaoshuBaby** [pokemonchw/dieloli#22]
Here is the console screenshot of this problem
![图片](https://user-images.githubusercontent.com/42690037/89093495-9e041900-d3ed-11ea-8731-05c2306943e5.png)
Here is my environment
OS 版本:          10.0.18362 暂缺 Build 18362
Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2201 Mhz
python --version             Python 3.8.3
pip --version                   pip 20.1.1 from c:\program files (x86)\python\lib\site-packages\pip (python 3.8)

**Comment by LaoshuBaby** [comment]
Text In Picture
________________________________________________

PS E:\FDM\dieloli-master> pip install -r requirements.txt                                                               Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: Dijkstar==2.4.0 in c:\users\快乐的老鼠宝宝\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: psutil==5.6.6 in c:\users\快乐的老鼠宝宝\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 2)) (5.6.6)
Requirement already satisfied: wcwidth==0.1.7 in c:\users\快乐的老鼠宝宝\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 3)) (0.1.7)
Requirement already satisfied: numpy==1.17.2 in c:\users\快乐的老鼠宝宝\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 4)) (1.17.2)
Requirement already satisfied: Pillow>=6.2.2 in c:\users\快乐的老鼠宝宝\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 5)) (7.2.0)
Requirement already satisfied: python_dateutil==2.8.0 in c:\users\快乐的老鼠宝宝\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 6)) (2.8.0)
Requirement already satisfied: six>=1.5 in c:\program files (x86)\python\lib\site-packages (from python_dateutil==2.8.0->-r requirements.txt (line 6)) (1.15.0)
WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
You should consider upgrading via the 'c:\program files (x86)\python\python.exe -m pip install --upgrade pip' command.
PS E:\FDM\dieloli-master> python game.py                                                                                Traceback (most recent call last):
  File "game.py", line 7, in <module>
    import freetype
ModuleNotFoundError: No module named 'freetype'
PS E:\FDM\dieloli-master> pip install freetype                                                                          Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement freetype (from versions: none)
ERROR: No matching distribution found for freetype
WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
You should consider upgrading via the 'c:\program files (x86)\python\python.exe -m pip install --upgrade pip' command.

**Comment by pokemonchw** [comment]
c:\program files (x86)\python\python.exe -m pip install --upgrade pip
please

**Comment by amtoaer** [comment]
这和 pip 的版本无关，在安装`freetype-py`后游戏即可正常运行。
或许应该把`freetype-py`依赖加入到requirements.txt中？

**Comment by Aloxaf** [comment]
> 这和 pip 的版本无关，在安装`freetype-py`后游戏即可正常运行。
> 或许应该把`freetype-py`依赖加入到requirements.txt中？

确实，我也遇到了这个问题，添加 freetype-py 后成功

@pokemonchw

**Comment by pokemonchw** [comment]
freetype是由于古代版本引入而未曾更新requirements导致的，在master分支的最新版本中，是一个无用依赖，现在开发在instability分支中持续进行，已与master分支内容差异巨大，所以暂时放弃对master分支进行更新，想要试玩master中的预览版本可以手动移除game.py第七行的import freetype

**Comment by Aloxaf** [comment]
哦对我都忘了这茬了，建议在 README 写一下或者切换一下主分支（

不过 instability 也少写了依赖：ephem
