### ISSUE TITLE
希望能用PyInstaller打包成exe

### ISSUE THREAD

**Issue by jojo253** [pokemonchw/dieloli#27]
用Windows和Ubuntu的机器都在pip安装包的时候就报错了，Google找了半天也没有解决方法，毕竟3.9实在太新了。
顺便问一下有没有讨论群。

Windows 上的问题是ephem最多只能装到3.7.6

PS D:\Downloads\pyephem-3.7.7.1> python -X utf8 -m pip install --upgrade ephem                                                                                                               Requirement already satisfied: ephem in c:\users\moyuge\appdata\local\programs\python\python39\lib\site-packages (3.7.6.0)                                                                   Collecting ephem                                                                                                                                                                               Using cached ephem-3.7.7.1.tar.gz (745 kB)                                                                                                                                                     ERROR: Command errored out with exit status 1:                                                                                                                                                command: 'C:\Users\moyuge\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\moyuge\\AppData\\Local\\Temp\\pip-install-vvdqk4j_\\ephem_399ca4c300cd4d8597700670ecf044c1\\setup.py'"'"'; __file__='"'"'C:\\Users\\moyuge\\AppData\\Local\\Temp\\pip-install-vvdqk4j_\\ephem_399ca4c300cd4d8597700670ecf044c1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\moyuge\AppData\Local\Temp\pip-pip-egg-info-4dw29tw4'                                                                                                                                      cwd: C:\Users\moyuge\AppData\Local\Temp\pip-install-vvdqk4j_\ephem_399ca4c300cd4d8597700670ecf044c1\                                                                                    Complete output (7 lines):                                                                                                                                                                   Traceback (most recent call last):                                                                                                                                                             File "<string>", line 1, in <module>                                                                                                                                                         File "C:\Users\moyuge\AppData\Local\Temp\pip-install-vvdqk4j_\ephem_399ca4c300cd4d8597700670ecf044c1\setup.py", line 40, in <module>                                                           long_description = read('README.rst'),                                                                                                                                                     File "C:\Users\moyuge\AppData\Local\Temp\pip-install-vvdqk4j_\ephem_399ca4c300cd4d8597700670ecf044c1\setup.py", line 27, in read                                                               return open(os.path.join(os.path.dirname(__file__), *filenames)).read()                                                                                                                  UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 4723: illegal multibyte sequence                                                                                          ----------------------------------------  

Ubuntu上根本没有原装python3.9，装了之后强行python3.9 -m pip install -r requirements.txt就报错一大堆

**Comment by pokemonchw** [comment]
现在游戏还在开发ing，最近两三个月会进行第一次打包～敬请期待

**Comment by MingFan789** [comment]
我用python3.8.5成功用pyinstaller 打包成.exe 了.

**Comment by pokemonchw** [comment]
现在已经有自动打包了～
