### ISSUE TITLE
教职工111宿舍 查看公共地图 崩溃

### ISSUE THREAD

**Issue by poly000** [pokemonchw/dieloli#57]
版本： git
[error.log](https://github.com/pokemonchw/dieloli/files/6254639/error.log)

**Comment by pokemonchw** [comment]
ummm或许可以贴一下你的存档文件给我？我至今没能复现这个问题

**Comment by poly000** [comment]
> ummm或许可以贴一下你的存档文件给我？我至今没能复现这个问题

[0.zip](https://github.com/pokemonchw/dieloli/files/6255429/0.zip)

**Comment by pokemonchw** [comment]
> > ummm或许可以贴一下你的存档文件给我？我至今没能复现这个问题
> 
> [0.zip](https://github.com/pokemonchw/dieloli/files/6255429/0.zip)

这是一个空的压缩包？

**Comment by poly000** [comment]
> > > ummm或许可以贴一下你的存档文件给我？我至今没能复现这个问题
> > 
> > 
> > [0.zip](https://github.com/pokemonchw/dieloli/files/6255429/0.zip)
> 
> 这是一个空的压缩包？

…… 我重压一下

**Comment by pokemonchw** [comment]
感谢，已修复
