### ISSUE TITLE
对小学生摸胸崩溃

### ISSUE THREAD

**Issue by poly000** [pokemonchw/dieloli#58]
版本：git
[error.log](https://github.com/pokemonchw/dieloli/files/6254684/error.log)

**Comment by poly000** [comment]
[error.log](https://github.com/pokemonchw/dieloli/files/6254687/error.log)
牵手也崩溃了……

**Comment by pokemonchw** [comment]
看上去是存档损坏……windows下自动存档受系统和cpu限制(不支持fork模式让子进程直接继承数据)，数据传递给子进程的速度很慢，今天改这版看来也8太行……看来只能放弃自动存档了

**Comment by pokemonchw** [comment]
感谢反馈，看上去是特定数值下的ui异常，我做了一次更新，可以保留存档再次尝试～

**Comment by poly000** [comment]
又崩溃惹 （抚摸）
[error.log](https://github.com/pokemonchw/dieloli/files/6255575/error.log)

**Comment by pokemonchw** [comment]
色欲的数值没设计好，你这是数值把ui摸炸了...ummmmmm，我先修一下它，更具体的，就等我后天更新吧
