### ISSUE TITLE
新游戏开档闪退

### ISSUE THREAD

**Issue by asbelong** [pokemonchw/dieloli#86]
开新档才会闪退，两个窗口正常出现。
加载存档因为把老存档也删了所以不清楚会不会出问题。
错误文件附下
[error.log](https://github.com/pokemonchw/dieloli/files/6568950/error.log)

系统是win10，游戏是最新的版本。

**Comment by pokemonchw** [comment]
提供一下版本号？

**Comment by asbelong** [comment]
> 
> 
> 提供一下版本号？

游戏版本号 2021.5.31.5
版本	Windows 10 专业版
版本号	20H2

**Comment by pokemonchw** [comment]
可以再试一试吗，我又更了一版，目前实在没定位到问题，看log上写语法不支持，就试着更了一下打包机的python版本

**Comment by pokemonchw** [comment]
已修复
